// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2yc2OqGZA5CX1JCgAFc-7seDGfjmT-6g',
    appId: '1:940343041460:web:eb29fca40496c3d726e6e1',
    messagingSenderId: '940343041460',
    projectId: 'purlstores',
    authDomain: 'purlstores.firebaseapp.com',
    storageBucket: 'purlstores.firebasestorage.app',
    measurementId: 'G-65K6222JPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYSACIIqAe_N-T5BLgBoJcKZUud8crbHM',
    appId: '1:940343041460:android:86640fd5093e869526e6e1',
    messagingSenderId: '940343041460',
    projectId: 'purlstores',
    storageBucket: 'purlstores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBslt-aWFfLlP10CEelnIzCRobV6rTBqEk',
    appId: '1:940343041460:ios:6cf36332b67a338526e6e1',
    messagingSenderId: '940343041460',
    projectId: 'purlstores',
    storageBucket: 'purlstores.firebasestorage.app',
    iosBundleId: 'com.purl.stores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBslt-aWFfLlP10CEelnIzCRobV6rTBqEk',
    appId: '1:940343041460:ios:60f6aa9eff67321726e6e1',
    messagingSenderId: '940343041460',
    projectId: 'purlstores',
    storageBucket: 'purlstores.firebasestorage.app',
    iosBundleId: 'com.glowcart.glowcartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2yc2OqGZA5CX1JCgAFc-7seDGfjmT-6g',
    appId: '1:940343041460:web:a3b81b79f8e69d9f26e6e1',
    messagingSenderId: '940343041460',
    projectId: 'purlstores',
    authDomain: 'purlstores.firebaseapp.com',
    storageBucket: 'purlstores.firebasestorage.app',
    measurementId: 'G-CQVEPERV5H',
  );
}
