// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOXnPKHsJyck4C6UHjZIpiR8r13yB4tNA',
    appId: '1:255612064321:web:b80e5344d84ae96fe52cc0',
    messagingSenderId: '255612064321',
    projectId: 'purlstores-za',
    authDomain: 'purlstores-za.firebaseapp.com',
    storageBucket: 'purlstores-za.firebasestorage.app',
    measurementId: 'G-3ZBX3158MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO1HUqVUSODF-TQyRO2xI728mNMOGc6i4',
    appId: '1:255612064321:android:89298bc809fa0914e52cc0',
    messagingSenderId: '255612064321',
    projectId: 'purlstores-za',
    storageBucket: 'purlstores-za.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwmX4u_27cwgrOu0GTVvRIgJJ3Pu-1Xdg',
    appId: '1:255612064321:ios:69d8388b40ed28ebe52cc0',
    messagingSenderId: '255612064321',
    projectId: 'purlstores-za',
    storageBucket: 'purlstores-za.firebasestorage.app',
    iosClientId: '255612064321-8r11lhup4pgqfn7io55gbv73aht8qs6n.apps.googleusercontent.com',
    iosBundleId: 'com.purl.stores',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwmX4u_27cwgrOu0GTVvRIgJJ3Pu-1Xdg',
    appId: '1:255612064321:ios:8142b19416151bcfe52cc0',
    messagingSenderId: '255612064321',
    projectId: 'purlstores-za',
    storageBucket: 'purlstores-za.firebasestorage.app',
    iosClientId: '255612064321-q6d59p5ahtk988pa2hhbk142rqiqmnd5.apps.googleusercontent.com',
    iosBundleId: 'com.glowcart.glowcartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOXnPKHsJyck4C6UHjZIpiR8r13yB4tNA',
    appId: '1:255612064321:web:4f15d42460bfe5c3e52cc0',
    messagingSenderId: '255612064321',
    projectId: 'purlstores-za',
    authDomain: 'purlstores-za.firebaseapp.com',
    storageBucket: 'purlstores-za.firebasestorage.app',
    measurementId: 'G-2884PS477H',
  );

}